# Generated by Django 5.1.4 on 2025-04-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='badge_id',
            new_name='unique_id',
        ),
    ]
