# Generated by Django 5.1.4 on 2025-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_badge_id_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
